export const yuGothic: string;
export const rubrikNew: string;
export const wrapper: string;
export const content: string;
export const logo: string;
export const title: string;
export const credit: string;
export const groupName: string;
export const button: string;
